# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crearProgramacionVacunacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrearProgramacionVacunacion(object):
    def setupUi(self, CrearProgramacionVacunacion):
        CrearProgramacionVacunacion.setObjectName("CrearProgramacionVacunacion")
        CrearProgramacionVacunacion.setEnabled(True)
        CrearProgramacionVacunacion.resize(689, 372)
        self.centralwidget = QtWidgets.QWidget(CrearProgramacionVacunacion)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCrear = QtWidgets.QPushButton(self.centralwidget)
        self.btnCrear.setEnabled(False)
        self.btnCrear.setGeometry(QtCore.QRect(530, 190, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btnCrear.setFont(font)
        self.btnCrear.setObjectName("btnCrear")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mensaje = QtWidgets.QLabel(self.centralwidget)
        self.mensaje.setGeometry(QtCore.QRect(30, 260, 611, 31))
        self.mensaje.setObjectName("mensaje")
        self.buttonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAtras.setGeometry(QtCore.QRect(50, 310, 101, 31))
        self.buttonAtras.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.buttonAtras.setObjectName("buttonAtras")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 441, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.fechaInicio = QtWidgets.QDateEdit(self.centralwidget)
        self.fechaInicio.setEnabled(True)
        self.fechaInicio.setGeometry(QtCore.QRect(522, 120, 118, 36))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fechaInicio.setFont(font)
        self.fechaInicio.setObjectName("fechaInicio")
        CrearProgramacionVacunacion.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CrearProgramacionVacunacion)
        self.statusbar.setObjectName("statusbar")
        CrearProgramacionVacunacion.setStatusBar(self.statusbar)

        self.retranslateUi(CrearProgramacionVacunacion)
        QtCore.QMetaObject.connectSlotsByName(CrearProgramacionVacunacion)

    def retranslateUi(self, CrearProgramacionVacunacion):
        _translate = QtCore.QCoreApplication.translate
        CrearProgramacionVacunacion.setWindowTitle(_translate("CrearProgramacionVacunacion", "Crear programación de vacunación"))
        self.btnCrear.setText(_translate("CrearProgramacionVacunacion", "Crear"))
        self.label.setText(_translate("CrearProgramacionVacunacion", "Para registrar una nueva programación de citas, ingrese la siguiente información."))
        self.mensaje.setText(_translate("CrearProgramacionVacunacion", "<html><head/><body><p align=\"center\"><span style=\" color:#aa0000;\"><br/></span></p></body></html>"))
        self.buttonAtras.setText(_translate("CrearProgramacionVacunacion", "Atras"))
        self.label_2.setText(_translate("CrearProgramacionVacunacion", "Ingrese la fecha a partir de la cual desea vacunar "))
        self.fechaInicio.setDisplayFormat(_translate("CrearProgramacionVacunacion", "dd/MM/yyyy"))
