# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vacunarUsuario.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vacunarUsuario(object):
    def setupUi(self, vacunarUsuario):
        vacunarUsuario.setObjectName("vacunarUsuario")
        vacunarUsuario.setEnabled(True)
        vacunarUsuario.resize(751, 397)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        vacunarUsuario.setFont(font)
        vacunarUsuario.setMouseTracking(True)
        self.centralwidget = QtWidgets.QWidget(vacunarUsuario)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setEnabled(True)
        self.splitter_3.setGeometry(QtCore.QRect(110, 110, 1, 16))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setEnabled(True)
        self.label_12.setGeometry(QtCore.QRect(50, 100, 345, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.noId = QtWidgets.QLineEdit(self.centralwidget)
        self.noId.setEnabled(True)
        self.noId.setGeometry(QtCore.QRect(380, 100, 181, 35))
        self.noId.setObjectName("noId")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(570, 100, 100, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.mensaje = QtWidgets.QLabel(self.centralwidget)
        self.mensaje.setEnabled(True)
        self.mensaje.setGeometry(QtCore.QRect(50, 160, 611, 31))
        self.mensaje.setObjectName("mensaje")
        self.buttonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAtras.setEnabled(True)
        self.buttonAtras.setGeometry(QtCore.QRect(40, 210, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonAtras.setFont(font)
        self.buttonAtras.setObjectName("buttonAtras")
        vacunarUsuario.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(vacunarUsuario)
        self.statusbar.setObjectName("statusbar")
        vacunarUsuario.setStatusBar(self.statusbar)

        self.retranslateUi(vacunarUsuario)
        QtCore.QMetaObject.connectSlotsByName(vacunarUsuario)

    def retranslateUi(self, vacunarUsuario):
        _translate = QtCore.QCoreApplication.translate
        vacunarUsuario.setWindowTitle(_translate("vacunarUsuario", "MainWindow"))
        self.label_12.setText(_translate("vacunarUsuario", "Ingrese el documento de identidad"))
        self.pushButton.setText(_translate("vacunarUsuario", "Vacunar"))
        self.mensaje.setText(_translate("vacunarUsuario", "<html><head/><body><p align=\"center\"><span style=\" color:#aa0000;\"><br/></span></p></body></html>"))
        self.buttonAtras.setText(_translate("vacunarUsuario", "Atras"))
