# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'consultaTodoPlan.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConsultarTodoPlan(object):
    def setupUi(self, ConsultarTodoPlan):
        ConsultarTodoPlan.setObjectName("ConsultarTodoPlan")
        ConsultarTodoPlan.resize(850, 587)
        self.centralwidget = QtWidgets.QWidget(ConsultarTodoPlan)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 20, 291, 51))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 80, 750, 377))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(145)
        self.tableWidget.verticalHeader().setDefaultSectionSize(35)
        self.buttonAtras = QtWidgets.QPushButton(self.centralwidget)
        self.buttonAtras.setGeometry(QtCore.QRect(20, 500, 101, 31))
        self.buttonAtras.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.buttonAtras.setObjectName("buttonAtras")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 500, 541, 31))
        self.label_2.setObjectName("label_2")
        self.btnBuscar = QtWidgets.QPushButton(self.centralwidget)
        self.btnBuscar.setGeometry(QtCore.QRect(670, 460, 101, 31))
        self.btnBuscar.setStyleSheet("background-color: rgb(208, 208, 208);")
        self.btnBuscar.setObjectName("btnBuscar")
        ConsultarTodoPlan.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ConsultarTodoPlan)
        self.statusbar.setObjectName("statusbar")
        ConsultarTodoPlan.setStatusBar(self.statusbar)

        self.retranslateUi(ConsultarTodoPlan)
        QtCore.QMetaObject.connectSlotsByName(ConsultarTodoPlan)

    def retranslateUi(self, ConsultarTodoPlan):
        _translate = QtCore.QCoreApplication.translate
        ConsultarTodoPlan.setWindowTitle(_translate("ConsultarTodoPlan", "MainWindow"))
        self.label.setText(_translate("ConsultarTodoPlan", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">Planes de Vacunación</span></p></body></html>"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("ConsultarTodoPlan", "Id. del plan"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("ConsultarTodoPlan", "Edad minima"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("ConsultarTodoPlan", "Edad maxima"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("ConsultarTodoPlan", "Fecha de inicio"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("ConsultarTodoPlan", "Fecha de finalización"))
        self.buttonAtras.setText(_translate("ConsultarTodoPlan", "Atras"))
        self.label_2.setText(_translate("ConsultarTodoPlan", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btnBuscar.setText(_translate("ConsultarTodoPlan", "Cargar data"))
