# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'crearProgramacionVacunacion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CrearProgramacionVacunacion(object):
    def setupUi(self, CrearProgramacionVacunacion):
        CrearProgramacionVacunacion.setObjectName("CrearProgramacionVacunacion")
        CrearProgramacionVacunacion.setEnabled(True)
        CrearProgramacionVacunacion.resize(689, 372)
        self.centralwidget = QtWidgets.QWidget(CrearProgramacionVacunacion)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(530, 190, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setEnabled(False)
        self.splitter_3.setGeometry(QtCore.QRect(40, 120, 611, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.splitter_3.setFont(font)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.splitter = QtWidgets.QSplitter(self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.splitter.setFont(font)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_3)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.fechaVencimiento_3 = QtWidgets.QDateEdit(self.splitter_2)
        self.fechaVencimiento_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fechaVencimiento_3.setFont(font)
        self.fechaVencimiento_3.setObjectName("fechaVencimiento_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 571, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 260, 611, 31))
        self.label_3.setObjectName("label_3")
        CrearProgramacionVacunacion.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CrearProgramacionVacunacion)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 689, 21))
        self.menubar.setObjectName("menubar")
        self.menuVolver = QtWidgets.QMenu(self.menubar)
        self.menuVolver.setObjectName("menuVolver")
        CrearProgramacionVacunacion.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CrearProgramacionVacunacion)
        self.statusbar.setObjectName("statusbar")
        CrearProgramacionVacunacion.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuVolver.menuAction())

        self.retranslateUi(CrearProgramacionVacunacion)
        QtCore.QMetaObject.connectSlotsByName(CrearProgramacionVacunacion)

    def retranslateUi(self, CrearProgramacionVacunacion):
        _translate = QtCore.QCoreApplication.translate
        CrearProgramacionVacunacion.setWindowTitle(_translate("CrearProgramacionVacunacion", "Crear programación de vacunación"))
        self.pushButton_2.setText(_translate("CrearProgramacionVacunacion", "Guardar"))
        self.label_2.setText(_translate("CrearProgramacionVacunacion", "Ingrese la fecha a partir de la cual desea vacunar "))
        self.fechaVencimiento_3.setDisplayFormat(_translate("CrearProgramacionVacunacion", "dd/MM/yyyy"))
        self.label.setText(_translate("CrearProgramacionVacunacion", "Para registrar una nueva programación de citas, ingrese la siguiente información."))
        self.label_3.setText(_translate("CrearProgramacionVacunacion", "<html><head/><body><p align=\"center\"><span style=\" color:#aa0000;\"><br/></span></p></body></html>"))
        self.menuVolver.setTitle(_translate("CrearProgramacionVacunacion", "Volver"))
